export const reduxConstants = {
  CART_LIST: 'CART_LIST',
  USER: 'USER',
  USER_ADDRESS: 'USER_ADDRESS',
  SHOW_LOCATION_DIALOG: 'SHOW_LOCATION_DIALOG',
  LOCATION_CITY: 'LOCATION_CITY',
  SHOW_CART_AS_DIALOG: 'SHOW_CART_AS_DIALOG',
};
