export const reduxConstants = {
  CART_LIST: 'CART_LIST',
  CART_RESOLUTION_TIME: 'CART_RESOLUTION_TIME',
  CART_RESOLVED_BOOLEAN: 'CART_RESOLVED_BOOLEAN',
  USER: 'USER',
  USER_ADDRESS: 'USER_ADDRESS',
  SHOW_LOCATION_DIALOG: 'SHOW_LOCATION_DIALOG',
  LOCATION_CITY: 'LOCATION_CITY',
  LOCATION_REGION: 'LOCATION_REGION',
  SHOW_CART_AS_DIALOG: 'SHOW_CART_AS_DIALOG',
};
